version: '3.4'

services:
    db:
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
          - ACCEPT_EULA=Y
          - MSSQL_SA_PASSWORD=MyPass@word
        ports:
            - "1433:1433"
        restart: always
    sonsmagicos.api:
        image: ${DOCKER_REGISTRY-}sonsmagicosapi
        build:
            context: .
            dockerfile: SonsMagicos.Api/Dockerfile
        restart: always
        depends_on:
          - db